// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBibvwpzwI1B5bvHrhxTDxfY5TkiQpXsI',
    appId: '1:423370771931:web:34ca359aecc83f7df86bfe',
    messagingSenderId: '423370771931',
    projectId: 'todo-app-ebd5d',
    authDomain: 'todo-app-ebd5d.firebaseapp.com',
    storageBucket: 'todo-app-ebd5d.firebasestorage.app',
    measurementId: 'G-TBBRTLYNQZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgORuJrTbQUhJSVJprgPUBBJdT79Cq_2A',
    appId: '1:423370771931:android:ac512e206cc18216f86bfe',
    messagingSenderId: '423370771931',
    projectId: 'todo-app-ebd5d',
    storageBucket: 'todo-app-ebd5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT-dirQYvreCFLIw4pdRY4JjpcfnXGpaI',
    appId: '1:423370771931:ios:7c334e393d89d2a1f86bfe',
    messagingSenderId: '423370771931',
    projectId: 'todo-app-ebd5d',
    storageBucket: 'todo-app-ebd5d.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT-dirQYvreCFLIw4pdRY4JjpcfnXGpaI',
    appId: '1:423370771931:ios:7c334e393d89d2a1f86bfe',
    messagingSenderId: '423370771931',
    projectId: 'todo-app-ebd5d',
    storageBucket: 'todo-app-ebd5d.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBibvwpzwI1B5bvHrhxTDxfY5TkiQpXsI',
    appId: '1:423370771931:web:e20a88d65fc51a7df86bfe',
    messagingSenderId: '423370771931',
    projectId: 'todo-app-ebd5d',
    authDomain: 'todo-app-ebd5d.firebaseapp.com',
    storageBucket: 'todo-app-ebd5d.firebasestorage.app',
    measurementId: 'G-DDGLCKKMBE',
  );
}
